# Handling Errors



Indented flow is for errors





``` go
func CountLines(r io.Reader) (int, error) {
  sc := bufio.NewScanner(r)
  lines := 0
  
  for sc.Scan() {
    lines ++
  }
  // sc.Err(), mysql Rows.Err() 一定不能丢弃
  return lines, sc.Err()
}
```





# Wrap errors



还记得之前我们 auth 的代码吧，如果 *authenticate* 返回错误，则 *AuthenticateRequest* 会将错误返回给调用方，调用者可能也会这样做，依此类推。在程序的顶部，程序的主体将把错误打印到屏幕或日志文件中，打印出来的只是：没有这样的文件或目录。







You should only handle errors once. Handling an error means inspecting the error value, and making a single decision.



不好的做法

我们经常发现类似的代码，在错误处理中，带了两个任务: 记录日志并且再次返回错误。 

``` go
func WriteAll(w io.Writer, buf []byte) error {
  _, err := w.Write(buf)
  if err != nil {
    log.Println("unable to write:", err) // annootated error goes to log file
    return err
  }
  
  return nil 
}
```



在这个例子中，如果在 *w.Write* 过程中发生了一个错误，那么一行代码将被写入日志文件中，记录错误发生的文件和行，并且错误也会返回给调用者，调用者可能会记录并返回它，一直返回到程序的顶部。



不包装的情况下

``` go
func main() {
  err := WriteConfig(f, &conf)
  fmt.Println(err)
}
```





Go 中的错误处理契约规定，在出现错误的情况下，不能对其他返回值的内容做出任何假设。由于 JSON 序列化失败，*buf* 的内容是未知的，可能它不包含任何内容，但更糟糕的是，它可能包含一个半写的 JSON 片段。

由于程序员在检查并记录错误后忘记 *return*，损坏的缓冲区将被传递给 *WriteAll*，这可能会成功，因此配置文件将被错误地写入。但是，该函数返回的结果是正确的。

![image-20220822164633164](/Users/kestrel/developer/nrookie.github.io/collections/go/xunlianying/errors/image-20220822164633164.png)







日志记录与错误无关且对调试没有帮助的信息应被视为噪音，应予以质疑。记录的原因是因为某些东西失败了，而日志包含了答案。





- *The error has been logged.*
- *The application is back to 100% integrity.*
- *The current error is not reported any longer.*



- 错误要被日志记录。
- 应用程序处理错误，保证*100%*完整性。
- 之后不再报告当前错误。



``` go
func Write(w io.Write, buf []byte) error {
  _, err := w.Write(buf)
  return errors.Wrap(err, "write failed")
}
```







- 在你的应用代码中，使用 *errors.New* 或者 *errros.Errorf* 返回错误。

- 如果调用其他包内的函数，通常简单的直接返回。
- 如果和其他库进行协作，考虑使用 *errors.Wrap* 或者 *errors.Wrapf* 保存堆栈信息。同样适用于和标准库协作的时候。 

- 直接返回错误，而不是每个错误产生的地方到处打日志。
- 在程序的顶部或者是工作的 goroutine 顶部（请求入口），使用 *%+v* 把堆栈详情记录。



- 使用 *errors.Cause* 获取 root error，再进行和 sentinel error 判定。

## 总结

- Packages that are reusable across many projects only return root error values.

  选择 *wrap error* 是只有 ***applications*** 可以选择应用的策略。具有最高可重用性的包只能返回根错误值。此机制与 *Go* 标准库中使用的相同（*kit* 库的 *sql.ErrNoRows*）。

- If the error is not going to be handled, wrap and return up the call stack.

  这是关于函数*/*方法调用返回的每个错误的基本问题。如果函数*/*方法不打算处理错误，那么用足够的上下文 *wrap errors* 并将其返回到调用堆栈中。例如，额外的上下文可以是使用的输入参数或失败的查询语句。确定您记录的上下文是足够多还是太多的一个好方法是检查日志并验证它们在开发期间是否为您工作。

- Once an error is handled, it is not allowed to be passed up the call stack any longer.

  一旦确定函数*/*方法将处理错误，错误就不再是错误。如果函数*/*方法仍然需要发出返回，则它不能返回错误值。它应该只返回零（比如降级处理中，你返回了降级数据，然后需要 *return nil*）。



